# Generated by Django 5.1.6 on 2025-02-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='update',
            new_name='updated',
        ),
    ]
